### ISSUE TITLE
Transfer Wiki

### ISSUE THREAD

**Issue by vvarduhn** [exahype/exahype#1]

**Comment by svenk** [comment]
Actually [the ExaHyPE wiki associated to the git repository at LRZ](https://gitlab.lrz.de/gi26det/ExaHyPE/wikis/pages) allows [git access](https://gitlab.lrz.de/gi26det/ExaHyPE/wikis/git_access) just as the [github wiki does](https://github.com/exahype/exahype/wiki). The two URLs are:

```
git clone git@gitlab.lrz.de:gi26det/ExaHyPE.wiki.git
git clone https://github.com/exahype/exahype.wiki.git
```

Both support Markdown, so both the *transfer* and also *syncing* the repositories is possible without any conversion or so.

However, I wonder whether it is useful just to *mirror* the (currently only very basic) information of the wiki. With the same argument, we could (probably) go and also clone all tickets from the gitlab. I feel we will end with a kind of chaos when we have basically the full infrastructure of git repository, tickets and wiki at both the LRZ gitlab and the public github.

In my opinion, instead, there should be a well mantainable *central* and *public* developer documentation infrastructure, like a public wiki installation (ie. MoinMoin or MediaWiki) at http://dev.exahype.eu.

**Comment by vvarduhn** [comment]
For the moment, I would like to keep only the gitlab@lrz version. As soon as we have a first public version of the code, we shoul transfer the wiki to GitHub and keep it (only) here
